config/routes.rb
Rails.application.routes.draw do
  get 'shorten_url/index'
  
  post 'shorten_url/index', to: 'shorten_url#generate'
  get 'shorten_url/debug', to: 'shorten_url#debug'

  get '/s/:short_code', to: 'shorten_url#redirect_url', as: 'shorten_url'

  root 'shorten_url#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shrunken_url.rb
class ShrunkenUrl < ApplicationRecord
    validates :url, presence: true
    validates :short_code, presence: true, uniqueness: true
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shorten_url_controller.rb
class ShortenUrlController < ApplicationController
  def index
  end

  def generate
    #byebug


    #@shrunkenUrl = ShrunkenUrl.create(
    #  url: params["url"], 
    #  short_code: rand(1..999999)
    #  #short_code: "T1"      
    #)
    
    @shrunkenUrl = ShrunkenUrl.new
    @shrunkenUrl.url = params["url"]
    @shrunkenUrl.short_code = generate_random_code
    
    continueSearch = true
    tries = 0

    # #try many times if the random code is already taken
    while continueSearch do
      begin
        @shrunkenUrl.save!
        continueSearch = false
      rescue ActiveRecord::RecordInvalid => e        
        if e.message == 'Validation failed: Short code has already been taken'
          @shrunkenUrl.short_code = generate_random_code          
          tries += 1

          logger.debug "Tries #{tries}"
          if tries >=  Rails.configuration.short_code_generator_max_tries 
            continueSearch = false
          end 
        else
          continueSearch = false         
        end
      end
    end

    render "index"
    #render plain: @shrunkenUrl.inspect        
  end 

  def redirect_url
    @shrunkenUrl = ShrunkenUrl.find_by(short_code: params["short_code"])
    if @shrunkenUrl
      redirect_to @shrunkenUrl.url
    else
      render plain: 'Not Found',  status: 404
    end
    
  end 
  
  def debug
    byebug
    render plain: "FINISH DEBUGGING!"        
  end

  private
    def generate_random_code      
      numberRecords = ShrunkenUrl.count 
      if numberRecords == 0 
        numberRecords = 1
      end

      options = Rails.configuration.short_code_generator_char_options
      numberOptions = options.length
      probabilityRepeated = Rails.configuration.short_code_generator_max_probability_repeated
      minimumSpace = (numberRecords/probabilityRepeated).ceil()

      lengthCode = Math::log(minimumSpace,numberOptions).ceil()

      code = ""
      while code.length < lengthCode do
        code += options.sample
      end

      return code
    end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorten_url_helper.rb
module ShortenUrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Histu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shorten_url/index.html.erb
<h1>HIStU</h1>
<h3>Honey, I Shrunk the Urls - Url Shortener</h3>

<%= form_with local: true do |form| %>
  <div class="form_container">    
    <%= form.url_field :url, value: (@shrunkenUrl.url if @shrunkenUrl), placeholder: "Please insert the url to generate short code" %>
    <%= form.submit "Generate Short Code", id:"generateButton", class:"button_primary" %>
  </div>  
<% end %>

<% if @shrunkenUrl %>
  <% if @shrunkenUrl.errors.any? %>
  <div id="error_explanation">
      <h2>
      <%= pluralize(@shrunkenUrl.errors.count, "error") %> prohibited
      this url from being shrunken:
      </h2>
      <ul>
      <% @shrunkenUrl.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
  <% else %>    
      <div id="containerShortenUrl">
        <%= link_to request.host_with_port()+shorten_url_path(@shrunkenUrl.short_code), shorten_url_path(@shrunkenUrl.short_code), target: :_blank, id: "shorthen_url" %>    
        <button class="clipboard-btn button_secondary" onclick="const url = document.getElementById('shorthen_url').href; navigator.clipboard.writeText(url)">
            Copy to clipboard
        </button>
      </div>
  <% end %>
<% end %>